include: package:flutter_lints/flutter.yaml


linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_positional_boolean_parameters
    - cancel_subscriptions
    - matching_super_parameters
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_final_locals
    - prefer_const_constructors
    - sized_box_shrink_expand