name: dsa_learning
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  #service locator
  get_it: ^8.0.3

  #state management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  #animations
  lottie: ^3.3.1

  #network client
  dio: ^5.7.0

  #localization
  easy_localization: ^3.0.7+1

  #local storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.2

  #logger
  logger: ^2.5.0

  #images
  flutter_svg: ^2.0.17

  # widgets
  fl_chart: ^0.70.2
  dotted_line: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/localization/
    - assets/animations/
    - assets/images/
    - assets/images/streak/
    - assets/images/currency/
    - assets/images/achievements/
    - lib/core/localization/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          style: normal
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          style: normal
          weight: 700

