// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _es_ES = {
  "language": "Idioma",
  "deleteAccount": "Eliminar cuenta",
  "exit": "Salir",
  "aboutApp": "Acerca de la aplicación",
  "version": "Versión",
  "learnWith": "¡Aprende algoritmos y estructuras de datos con",
  "analiseProgress": "Analiza el progreso y los logros alcanzados con",
  "collectBytes": "Colecciona bytes, ventiladores y hash de",
  "DSA": "DSA Learn",
  "start": "Empezar",
  "signIn": "Iniciar sesión",
  "signUp": "Registrarse",
  "email": "Email",
  "password": "Contraseña"
};
static const Map<String,dynamic> _en_GB = {
  "language": "Language",
  "deleteAccount": "Delete Account",
  "exit": "Exit",
  "aboutApp": "About the App",
  "version": "Version",
  "learnWith": "Learn algorithms and data structures with",
  "analiseProgress": "Analyze progress and achievements made with",
  "collectBytes": "Collect bytes, fans, and hash learning with",
  "DSA": "DSA Learn",
  "start": "Start",
  "signIn": "Sign in",
  "signUp": "Sign up",
  "back": "Back",
  "email": "Email",
  "password": "Password"
};
static const Map<String,dynamic> _uk_UA = {
  "language": "Мова",
  "deleteAccount": "Видалити обліковий запис",
  "exit": "Вихід",
  "aboutApp": "Про застосунок",
  "version": "Версія",
  "learnWith": "Вивчай алгоритми та структури даних разом з",
  "analiseProgress": "Аналізуй прогрес та досягнення, здобуті з",
  "collectBytes": "Колекціонуй байти, вентилятори та хеш з",
  "DSA": "DSA Learn",
  "start": "Розпочати",
  "signIn": "Вхід",
  "signUp": "Реєстрація",
  "back": "Назад",
  "email": "Email",
  "password": "Пароль",
  "confirm": "Підтвердити",
  "name": "Ім'я",
  "authError": "Не вдалось здійснити вхід.",
  "helloUser": "Вітаю,",
  "manageCurrency": "Керувати валютою",
  "bytes": "Байти",
  "vents": "Вентилятори",
  "hash": "Хеш",
  "achievements": "Досягнення",
  "seeAll": "Переглянути усі",
  "statistics": "Статистика",
  "algorithms": "Алгоритми",
  "dataStructures": "Структури даних",
  "minutesQuantity": "*Кількість хвилин, присвячених навчанню",
  "sortingAlgorithms": "Алгоритми сортування",
  "addAvatar": "Додати аватар",
  "withCamera": "Зробити фото з камери",
  "fromGallery": "Обрати фото з галереї",
  "plan": "План",
  "game": "Гра",
  "savvy": "Кмітливість",
  "savvyDescription": "Модуль було завершено без помилок! Так тримати!",
  "devotion": "Відданість",
  "devotionDescription": "Не кожен зможе повернутись після пропущеного дня прогресу.",
  "junior": "Джуніор",
  "juniorDescription": "Ви знаєте усі алгоритми! Продовжуйте працювати!",
  "middle": "Мідл",
  "middleDescription": "Оце завзятість! Ви вивчили структури даних!",
  "persistence": "Наполегливість",
  "persistenceDescription": "Два модулі за один підхід - активний шлях до досягнення мети.",
  "responsibility": "Відповідальність",
  "responsibilityDescription": "Лише найвідповідальніші навчаються увесь тиждень!",
  "senior": "Сеньйор",
  "seniorDescription": "Ви виконали усі завдання! Тех-гуру",
  "yes": "Так",
  "no": "Ні",
  "doYouWantToExit": "Ви справді хочете вийти?",
  "loadingInformationBytes": "Завантажуємо байти інформації...",
  "next": "Далі",
  "pause": "Пауза",
  "niceJob": "Так тримати!",
  "allTheoryIsLearned": "Увесь теоретичний матеріал пройдено.",
  "reward": "Нагорода",
  "letsCheckTheKnowledge": "Перевіримо, наскільки добре він був засвоєний?",
  "later": "Пізніше",
  "letsGo": "Вперед!",
  "lessonIsOver": "Урок завершено!",
  "toLessons": "До навчання",
  "shop": "Магазин",
  "myBalance": "Мій баланс",
  "offers": "Пропозиції",
  "total": "Всього",
  "buyVentsToCoolSystem": "Вентилятори: охолодити систему та навчатись далі.",
  "buyHashToFreezeStreak": "Хеш: застосувати, аби відновити пропущений день",
  "endLesson": "Завершити урок",
  "doYouWantEndLesson": "Ви справді хочете завершити урок?",
  "allTheRewardsWillBeLost": "Усі нагороди за вивчення теорії буде втрачено :(",
  "streak": "Прогрес",
  "youMissedOneDay": "О ні, ви пропустили один день навчання(",
  "wouldYouLikeToUseHash": "Хочете використати Хеш, аби система забула про це?",
  "knowledgeCheck": "Перевірка знань",
  "buyAvatar": "Придбати аватар",
  "buy": "Придбати",
  "free": "Безкоштовно",
  "choose": "Обрати",
  "vibration": "Вібрація",
  "sound": "Звук",
  "ohNo": "О ні!",
  "youUsedAllTheVents": "Ви використали усі вентилятори :(",
  "wantBuyMore": "Хочете придбати ще?",
  "nextVentIn": "Наступний вентелятор через",
  "animations": "Анімації",
  "lessonIsNotOver": "Урок не завершено(",
  "dontLoseMotivation": "Не втрачайте духу!\nВи можете вивчити матеріал ще раз.",
  "justNCorrectAnswers": "Всього {count} правильних відповідей, аби завершити урок успішно.",
  "finish": "Завершити",
  "doYouWantDeleteAccount": "Ви справді хочете видалити акаунт?",
  "learnToSeeProgress": "Розпочни урок, аби побачити свій прогрес!",
  "tutorialStart": "Вітаю! Це застосунок для вивчення алгоритмів та структур даних.",
  "tutorialStep1": "Ось це - 「Домівка」",
  "tutorialStep1Description": "Тут знаходиться Ваш прогрес",
  "tutorialStep2": "У розділі 「Навчання」 підготовано для Вас уроки",
  "tutorialStep2Description": "Навчайтеся та отримуйте винагороди за успіхи!",
  "tutorialStep3": "У 「Профілі」розміщено налаштування",
  "tutorialStep3Description": "Саме тут Ви можете обрати комфортні для себе опції",
  "tutorialFinish": "Успіхів у навчанні! Зовсім скоро Ви станете справжнім професіоналом :)",
  "skip": "Пропустити",
  "somethingWentWrong": "Щось пішло не так(",
  "tryAgain": "Спробувати ще раз"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"es_ES": _es_ES, "en_GB": _en_GB, "uk_UA": _uk_UA};
}
